// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.17.3
// source: s.binance/proto/binance.proto

package binanceproto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	proto1 "swallowtail/s.trade-engine/proto"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type AssetPair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol            string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	BaseAsset         string `protobuf:"bytes,2,opt,name=base_asset,json=baseAsset,proto3" json:"base_asset,omitempty"`
	QuoteAsset        string `protobuf:"bytes,3,opt,name=quote_asset,json=quoteAsset,proto3" json:"quote_asset,omitempty"`
	WithSpotTrading   bool   `protobuf:"varint,4,opt,name=with_spot_trading,json=withSpotTrading,proto3" json:"with_spot_trading,omitempty"`
	WithMarginTrading bool   `protobuf:"varint,5,opt,name=with_margin_trading,json=withMarginTrading,proto3" json:"with_margin_trading,omitempty"`
}

func (x *AssetPair) Reset() {
	*x = AssetPair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_binance_proto_binance_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssetPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetPair) ProtoMessage() {}

func (x *AssetPair) ProtoReflect() protoreflect.Message {
	mi := &file_s_binance_proto_binance_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetPair.ProtoReflect.Descriptor instead.
func (*AssetPair) Descriptor() ([]byte, []int) {
	return file_s_binance_proto_binance_proto_rawDescGZIP(), []int{0}
}

func (x *AssetPair) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *AssetPair) GetBaseAsset() string {
	if x != nil {
		return x.BaseAsset
	}
	return ""
}

func (x *AssetPair) GetQuoteAsset() string {
	if x != nil {
		return x.QuoteAsset
	}
	return ""
}

func (x *AssetPair) GetWithSpotTrading() bool {
	if x != nil {
		return x.WithSpotTrading
	}
	return false
}

func (x *AssetPair) GetWithMarginTrading() bool {
	if x != nil {
		return x.WithMarginTrading
	}
	return false
}

type ListAllAssetPairsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListAllAssetPairsRequest) Reset() {
	*x = ListAllAssetPairsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_binance_proto_binance_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAllAssetPairsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllAssetPairsRequest) ProtoMessage() {}

func (x *ListAllAssetPairsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_s_binance_proto_binance_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllAssetPairsRequest.ProtoReflect.Descriptor instead.
func (*ListAllAssetPairsRequest) Descriptor() ([]byte, []int) {
	return file_s_binance_proto_binance_proto_rawDescGZIP(), []int{1}
}

type ListAllAssetPairsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssetPairs []*AssetPair `protobuf:"bytes,1,rep,name=asset_pairs,json=assetPairs,proto3" json:"asset_pairs,omitempty"`
}

func (x *ListAllAssetPairsResponse) Reset() {
	*x = ListAllAssetPairsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_binance_proto_binance_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAllAssetPairsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllAssetPairsResponse) ProtoMessage() {}

func (x *ListAllAssetPairsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_s_binance_proto_binance_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllAssetPairsResponse.ProtoReflect.Descriptor instead.
func (*ListAllAssetPairsResponse) Descriptor() ([]byte, []int) {
	return file_s_binance_proto_binance_proto_rawDescGZIP(), []int{2}
}

func (x *ListAllAssetPairsResponse) GetAssetPairs() []*AssetPair {
	if x != nil {
		return x.AssetPairs
	}
	return nil
}

type ExecuteNewFuturesPerpetualOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Order              *proto1.Order            `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Timestamp          *timestamppb.Timestamp   `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Credentials        *proto1.VenueCredentials `protobuf:"bytes,3,opt,name=credentials,proto3" json:"credentials,omitempty"`
	IsAccountHedgeMode bool                     `protobuf:"varint,4,opt,name=is_account_hedge_mode,json=isAccountHedgeMode,proto3" json:"is_account_hedge_mode,omitempty"`
}

func (x *ExecuteNewFuturesPerpetualOrderRequest) Reset() {
	*x = ExecuteNewFuturesPerpetualOrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_binance_proto_binance_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteNewFuturesPerpetualOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteNewFuturesPerpetualOrderRequest) ProtoMessage() {}

func (x *ExecuteNewFuturesPerpetualOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_s_binance_proto_binance_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteNewFuturesPerpetualOrderRequest.ProtoReflect.Descriptor instead.
func (*ExecuteNewFuturesPerpetualOrderRequest) Descriptor() ([]byte, []int) {
	return file_s_binance_proto_binance_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteNewFuturesPerpetualOrderRequest) GetOrder() *proto1.Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *ExecuteNewFuturesPerpetualOrderRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ExecuteNewFuturesPerpetualOrderRequest) GetCredentials() *proto1.VenueCredentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *ExecuteNewFuturesPerpetualOrderRequest) GetIsAccountHedgeMode() bool {
	if x != nil {
		return x.IsAccountHedgeMode
	}
	return false
}

type ExecuteNewFuturesPerpetualOrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Order *proto1.Order `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
}

func (x *ExecuteNewFuturesPerpetualOrderResponse) Reset() {
	*x = ExecuteNewFuturesPerpetualOrderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_binance_proto_binance_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteNewFuturesPerpetualOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteNewFuturesPerpetualOrderResponse) ProtoMessage() {}

func (x *ExecuteNewFuturesPerpetualOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_s_binance_proto_binance_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteNewFuturesPerpetualOrderResponse.ProtoReflect.Descriptor instead.
func (*ExecuteNewFuturesPerpetualOrderResponse) Descriptor() ([]byte, []int) {
	return file_s_binance_proto_binance_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteNewFuturesPerpetualOrderResponse) GetOrder() *proto1.Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type ExecuteNewSpotOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Order       *proto1.Order            `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Timestamp   *timestamppb.Timestamp   `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Credentials *proto1.VenueCredentials `protobuf:"bytes,3,opt,name=credentials,proto3" json:"credentials,omitempty"`
}

func (x *ExecuteNewSpotOrderRequest) Reset() {
	*x = ExecuteNewSpotOrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_binance_proto_binance_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteNewSpotOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteNewSpotOrderRequest) ProtoMessage() {}

func (x *ExecuteNewSpotOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_s_binance_proto_binance_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteNewSpotOrderRequest.ProtoReflect.Descriptor instead.
func (*ExecuteNewSpotOrderRequest) Descriptor() ([]byte, []int) {
	return file_s_binance_proto_binance_proto_rawDescGZIP(), []int{5}
}

func (x *ExecuteNewSpotOrderRequest) GetOrder() *proto1.Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *ExecuteNewSpotOrderRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ExecuteNewSpotOrderRequest) GetCredentials() *proto1.VenueCredentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type ExecuteNewSpotOrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Order *proto1.Order `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
}

func (x *ExecuteNewSpotOrderResponse) Reset() {
	*x = ExecuteNewSpotOrderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_binance_proto_binance_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteNewSpotOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteNewSpotOrderResponse) ProtoMessage() {}

func (x *ExecuteNewSpotOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_s_binance_proto_binance_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteNewSpotOrderResponse.ProtoReflect.Descriptor instead.
func (*ExecuteNewSpotOrderResponse) Descriptor() ([]byte, []int) {
	return file_s_binance_proto_binance_proto_rawDescGZIP(), []int{6}
}

func (x *ExecuteNewSpotOrderResponse) GetOrder() *proto1.Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type ReadPerpetualFuturesAccountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActorId     string                   `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Credentials *proto1.VenueCredentials `protobuf:"bytes,2,opt,name=credentials,proto3" json:"credentials,omitempty"`
}

func (x *ReadPerpetualFuturesAccountRequest) Reset() {
	*x = ReadPerpetualFuturesAccountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_binance_proto_binance_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadPerpetualFuturesAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadPerpetualFuturesAccountRequest) ProtoMessage() {}

func (x *ReadPerpetualFuturesAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_s_binance_proto_binance_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadPerpetualFuturesAccountRequest.ProtoReflect.Descriptor instead.
func (*ReadPerpetualFuturesAccountRequest) Descriptor() ([]byte, []int) {
	return file_s_binance_proto_binance_proto_rawDescGZIP(), []int{7}
}

func (x *ReadPerpetualFuturesAccountRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *ReadPerpetualFuturesAccountRequest) GetCredentials() *proto1.VenueCredentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type ReadPerpetualFuturesAccountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Asset            string                 `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	Balance          float32                `protobuf:"fixed32,2,opt,name=balance,proto3" json:"balance,omitempty"`
	AvailableBalance float32                `protobuf:"fixed32,3,opt,name=available_balance,json=availableBalance,proto3" json:"available_balance,omitempty"`
	LastUpdated      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
}

func (x *ReadPerpetualFuturesAccountResponse) Reset() {
	*x = ReadPerpetualFuturesAccountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_binance_proto_binance_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadPerpetualFuturesAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadPerpetualFuturesAccountResponse) ProtoMessage() {}

func (x *ReadPerpetualFuturesAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_s_binance_proto_binance_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadPerpetualFuturesAccountResponse.ProtoReflect.Descriptor instead.
func (*ReadPerpetualFuturesAccountResponse) Descriptor() ([]byte, []int) {
	return file_s_binance_proto_binance_proto_rawDescGZIP(), []int{8}
}

func (x *ReadPerpetualFuturesAccountResponse) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *ReadPerpetualFuturesAccountResponse) GetBalance() float32 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *ReadPerpetualFuturesAccountResponse) GetAvailableBalance() float32 {
	if x != nil {
		return x.AvailableBalance
	}
	return 0
}

func (x *ReadPerpetualFuturesAccountResponse) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

type GetLatestPriceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
}

func (x *GetLatestPriceRequest) Reset() {
	*x = GetLatestPriceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_binance_proto_binance_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLatestPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestPriceRequest) ProtoMessage() {}

func (x *GetLatestPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_s_binance_proto_binance_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestPriceRequest.ProtoReflect.Descriptor instead.
func (*GetLatestPriceRequest) Descriptor() ([]byte, []int) {
	return file_s_binance_proto_binance_proto_rawDescGZIP(), []int{9}
}

func (x *GetLatestPriceRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type GetLatestPriceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Price     float32 `protobuf:"fixed32,1,opt,name=price,proto3" json:"price,omitempty"`
	Timestamp int64   `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *GetLatestPriceResponse) Reset() {
	*x = GetLatestPriceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_binance_proto_binance_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLatestPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestPriceResponse) ProtoMessage() {}

func (x *GetLatestPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_s_binance_proto_binance_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestPriceResponse.ProtoReflect.Descriptor instead.
func (*GetLatestPriceResponse) Descriptor() ([]byte, []int) {
	return file_s_binance_proto_binance_proto_rawDescGZIP(), []int{10}
}

func (x *GetLatestPriceResponse) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GetLatestPriceResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type GetFundingRatesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol    string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	StartTime int64  `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   int64  `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Limit     int64  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetFundingRatesRequest) Reset() {
	*x = GetFundingRatesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_binance_proto_binance_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFundingRatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFundingRatesRequest) ProtoMessage() {}

func (x *GetFundingRatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_s_binance_proto_binance_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFundingRatesRequest.ProtoReflect.Descriptor instead.
func (*GetFundingRatesRequest) Descriptor() ([]byte, []int) {
	return file_s_binance_proto_binance_proto_rawDescGZIP(), []int{11}
}

func (x *GetFundingRatesRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetFundingRatesRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetFundingRatesRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *GetFundingRatesRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type FundingRateInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol          string  `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	FundingRate     float32 `protobuf:"fixed32,2,opt,name=funding_rate,json=fundingRate,proto3" json:"funding_rate,omitempty"`
	FundingRateTime float32 `protobuf:"fixed32,3,opt,name=funding_rate_time,json=fundingRateTime,proto3" json:"funding_rate_time,omitempty"`
}

func (x *FundingRateInfo) Reset() {
	*x = FundingRateInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_binance_proto_binance_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FundingRateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FundingRateInfo) ProtoMessage() {}

func (x *FundingRateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_s_binance_proto_binance_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FundingRateInfo.ProtoReflect.Descriptor instead.
func (*FundingRateInfo) Descriptor() ([]byte, []int) {
	return file_s_binance_proto_binance_proto_rawDescGZIP(), []int{12}
}

func (x *FundingRateInfo) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *FundingRateInfo) GetFundingRate() float32 {
	if x != nil {
		return x.FundingRate
	}
	return 0
}

func (x *FundingRateInfo) GetFundingRateTime() float32 {
	if x != nil {
		return x.FundingRateTime
	}
	return 0
}

type GetFundingRatesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FundingRates []*FundingRateInfo `protobuf:"bytes,1,rep,name=funding_rates,json=fundingRates,proto3" json:"funding_rates,omitempty"`
}

func (x *GetFundingRatesResponse) Reset() {
	*x = GetFundingRatesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_binance_proto_binance_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFundingRatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFundingRatesResponse) ProtoMessage() {}

func (x *GetFundingRatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_s_binance_proto_binance_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFundingRatesResponse.ProtoReflect.Descriptor instead.
func (*GetFundingRatesResponse) Descriptor() ([]byte, []int) {
	return file_s_binance_proto_binance_proto_rawDescGZIP(), []int{13}
}

func (x *GetFundingRatesResponse) GetFundingRates() []*FundingRateInfo {
	if x != nil {
		return x.FundingRates
	}
	return nil
}

type VerifyCredentialsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Credentials *proto1.VenueCredentials `protobuf:"bytes,1,opt,name=credentials,proto3" json:"credentials,omitempty"`
	UserId      string                   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *VerifyCredentialsRequest) Reset() {
	*x = VerifyCredentialsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_binance_proto_binance_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCredentialsRequest) ProtoMessage() {}

func (x *VerifyCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_s_binance_proto_binance_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCredentialsRequest.ProtoReflect.Descriptor instead.
func (*VerifyCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_s_binance_proto_binance_proto_rawDescGZIP(), []int{14}
}

func (x *VerifyCredentialsRequest) GetCredentials() *proto1.VenueCredentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *VerifyCredentialsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type VerifyCredentialsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success         bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ReadEnabled     bool   `protobuf:"varint,2,opt,name=read_enabled,json=readEnabled,proto3" json:"read_enabled,omitempty"`
	FuturesEnabled  bool   `protobuf:"varint,3,opt,name=futures_enabled,json=futuresEnabled,proto3" json:"futures_enabled,omitempty"`
	WithdrawEnabled bool   `protobuf:"varint,4,opt,name=withdraw_enabled,json=withdrawEnabled,proto3" json:"withdraw_enabled,omitempty"`
	SpotEnabled     bool   `protobuf:"varint,5,opt,name=spot_enabled,json=spotEnabled,proto3" json:"spot_enabled,omitempty"`
	OptionsEnabled  bool   `protobuf:"varint,6,opt,name=options_enabled,json=optionsEnabled,proto3" json:"options_enabled,omitempty"`
	IpRestrictions  bool   `protobuf:"varint,7,opt,name=ip_restrictions,json=ipRestrictions,proto3" json:"ip_restrictions,omitempty"`
	Reason          string `protobuf:"bytes,8,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *VerifyCredentialsResponse) Reset() {
	*x = VerifyCredentialsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_binance_proto_binance_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCredentialsResponse) ProtoMessage() {}

func (x *VerifyCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_s_binance_proto_binance_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCredentialsResponse.ProtoReflect.Descriptor instead.
func (*VerifyCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_s_binance_proto_binance_proto_rawDescGZIP(), []int{15}
}

func (x *VerifyCredentialsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VerifyCredentialsResponse) GetReadEnabled() bool {
	if x != nil {
		return x.ReadEnabled
	}
	return false
}

func (x *VerifyCredentialsResponse) GetFuturesEnabled() bool {
	if x != nil {
		return x.FuturesEnabled
	}
	return false
}

func (x *VerifyCredentialsResponse) GetWithdrawEnabled() bool {
	if x != nil {
		return x.WithdrawEnabled
	}
	return false
}

func (x *VerifyCredentialsResponse) GetSpotEnabled() bool {
	if x != nil {
		return x.SpotEnabled
	}
	return false
}

func (x *VerifyCredentialsResponse) GetOptionsEnabled() bool {
	if x != nil {
		return x.OptionsEnabled
	}
	return false
}

func (x *VerifyCredentialsResponse) GetIpRestrictions() bool {
	if x != nil {
		return x.IpRestrictions
	}
	return false
}

func (x *VerifyCredentialsResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GetStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_binance_proto_binance_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_s_binance_proto_binance_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_s_binance_proto_binance_proto_rawDescGZIP(), []int{16}
}

type GetStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The time recorded by the server on Binances side.
	ServerTime int64 `protobuf:"varint,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	// The time it took to receive the request response
	RequestLatency int64 `protobuf:"varint,2,opt,name=request_latency,json=requestLatency,proto3" json:"request_latency,omitempty"`
	// The assumed clock drift between the client & the server time
	AssumedClockDrift int64 `protobuf:"varint,3,opt,name=assumed_clock_drift,json=assumedClockDrift,proto3" json:"assumed_clock_drift,omitempty"`
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_binance_proto_binance_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_s_binance_proto_binance_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_s_binance_proto_binance_proto_rawDescGZIP(), []int{17}
}

func (x *GetStatusResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *GetStatusResponse) GetRequestLatency() int64 {
	if x != nil {
		return x.RequestLatency
	}
	return 0
}

func (x *GetStatusResponse) GetAssumedClockDrift() int64 {
	if x != nil {
		return x.AssumedClockDrift
	}
	return 0
}

var File_s_binance_proto_binance_proto protoreflect.FileDescriptor

var file_s_binance_proto_binance_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x73, 0x2e, 0x62, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x62, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x26, 0x73, 0x2e, 0x74, 0x72, 0x61, 0x64, 0x65, 0x2d, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x72, 0x61, 0x64, 0x65, 0x65, 0x6e, 0x67, 0x69,
	0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbf, 0x01, 0x0a, 0x09, 0x41, 0x73, 0x73,
	0x65, 0x74, 0x50, 0x61, 0x69, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x1d,
	0x0a, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x62, 0x61, 0x73, 0x65, 0x41, 0x73, 0x73, 0x65, 0x74, 0x12, 0x1f, 0x0a,
	0x0b, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x5f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x41, 0x73, 0x73, 0x65, 0x74, 0x12, 0x2a,
	0x0a, 0x11, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x73, 0x70, 0x6f, 0x74, 0x5f, 0x74, 0x72, 0x61, 0x64,
	0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x77, 0x69, 0x74, 0x68, 0x53,
	0x70, 0x6f, 0x74, 0x54, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x2e, 0x0a, 0x13, 0x77, 0x69,
	0x74, 0x68, 0x5f, 0x6d, 0x61, 0x72, 0x67, 0x69, 0x6e, 0x5f, 0x74, 0x72, 0x61, 0x64, 0x69, 0x6e,
	0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x77, 0x69, 0x74, 0x68, 0x4d, 0x61, 0x72,
	0x67, 0x69, 0x6e, 0x54, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x22, 0x1a, 0x0a, 0x18, 0x4c, 0x69,
	0x73, 0x74, 0x41, 0x6c, 0x6c, 0x41, 0x73, 0x73, 0x65, 0x74, 0x50, 0x61, 0x69, 0x72, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x48, 0x0a, 0x19, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c,
	0x6c, 0x41, 0x73, 0x73, 0x65, 0x74, 0x50, 0x61, 0x69, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x0b, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x70, 0x61, 0x69,
	0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74,
	0x50, 0x61, 0x69, 0x72, 0x52, 0x0a, 0x61, 0x73, 0x73, 0x65, 0x74, 0x50, 0x61, 0x69, 0x72, 0x73,
	0x22, 0xe8, 0x01, 0x0a, 0x26, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x46,
	0x75, 0x74, 0x75, 0x72, 0x65, 0x73, 0x50, 0x65, 0x72, 0x70, 0x65, 0x74, 0x75, 0x61, 0x6c, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x05, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x33, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61,
	0x6c, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x56, 0x65, 0x6e, 0x75, 0x65,
	0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x0b, 0x63, 0x72, 0x65,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x12, 0x31, 0x0a, 0x15, 0x69, 0x73, 0x5f, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x68, 0x65, 0x64, 0x67, 0x65, 0x5f, 0x6d, 0x6f, 0x64,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x12, 0x69, 0x73, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x48, 0x65, 0x64, 0x67, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x22, 0x47, 0x0a, 0x27, 0x45,
	0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x46, 0x75, 0x74, 0x75, 0x72, 0x65, 0x73,
	0x50, 0x65, 0x72, 0x70, 0x65, 0x74, 0x75, 0x61, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x05, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x22, 0xa9, 0x01, 0x0a, 0x1a, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65,
	0x4e, 0x65, 0x77, 0x53, 0x70, 0x6f, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x06, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x33, 0x0a, 0x0b, 0x63,
	0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x56, 0x65, 0x6e, 0x75, 0x65, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x61, 0x6c, 0x73, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73,
	0x22, 0x3b, 0x0a, 0x1b, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x53, 0x70,
	0x6f, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1c, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06,
	0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x22, 0x74, 0x0a,
	0x22, 0x52, 0x65, 0x61, 0x64, 0x50, 0x65, 0x72, 0x70, 0x65, 0x74, 0x75, 0x61, 0x6c, 0x46, 0x75,
	0x74, 0x75, 0x72, 0x65, 0x73, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x33,
	0x0a, 0x0b, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x56, 0x65, 0x6e, 0x75, 0x65, 0x43, 0x72, 0x65, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x61, 0x6c, 0x73, 0x22, 0xc1, 0x01, 0x0a, 0x23, 0x52, 0x65, 0x61, 0x64, 0x50, 0x65, 0x72, 0x70,
	0x65, 0x74, 0x75, 0x61, 0x6c, 0x46, 0x75, 0x74, 0x75, 0x72, 0x65, 0x73, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61,
	0x73, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x73, 0x73, 0x65,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x2b, 0x0a, 0x11, 0x61,
	0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x10, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c,
	0x65, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x3d, 0x0a, 0x0c, 0x6c, 0x61, 0x73, 0x74,
	0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x6c, 0x61, 0x73, 0x74,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x22, 0x2f, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4c, 0x61,
	0x74, 0x65, 0x73, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x22, 0x4c, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x4c,
	0x61, 0x74, 0x65, 0x73, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x80, 0x01, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x46, 0x75,
	0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x78, 0x0a, 0x0f, 0x46, 0x75, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x52, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79,
	0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x75, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5f,
	0x72, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x66, 0x75, 0x6e, 0x64,
	0x69, 0x6e, 0x67, 0x52, 0x61, 0x74, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x66, 0x75, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x0f, 0x66, 0x75, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x61, 0x74, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x22, 0x50, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x46, 0x75, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x52, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35,
	0x0a, 0x0d, 0x66, 0x75, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x46, 0x75, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52,
	0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x66, 0x75, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x52, 0x61, 0x74, 0x65, 0x73, 0x22, 0x68, 0x0a, 0x18, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43,
	0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x33, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x56, 0x65, 0x6e, 0x75, 0x65, 0x43, 0x72,
	0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22,
	0xb9, 0x02, 0x0a, 0x19, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x61, 0x64, 0x5f,
	0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x72,
	0x65, 0x61, 0x64, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x66, 0x75,
	0x74, 0x75, 0x72, 0x65, 0x73, 0x5f, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0e, 0x66, 0x75, 0x74, 0x75, 0x72, 0x65, 0x73, 0x45, 0x6e, 0x61, 0x62,
	0x6c, 0x65, 0x64, 0x12, 0x29, 0x0a, 0x10, 0x77, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x5f,
	0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x77,
	0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x21,
	0x0a, 0x0c, 0x73, 0x70, 0x6f, 0x74, 0x5f, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x73, 0x70, 0x6f, 0x74, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65,
	0x64, 0x12, 0x27, 0x0a, 0x0f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x65, 0x6e, 0x61,
	0x62, 0x6c, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x69, 0x70,
	0x5f, 0x72, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0e, 0x69, 0x70, 0x52, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x12, 0x0a, 0x10, 0x47,
	0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x8d, 0x01, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x5f, 0x6c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x12,
	0x2e, 0x0a, 0x13, 0x61, 0x73, 0x73, 0x75, 0x6d, 0x65, 0x64, 0x5f, 0x63, 0x6c, 0x6f, 0x63, 0x6b,
	0x5f, 0x64, 0x72, 0x69, 0x66, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x61, 0x73,
	0x73, 0x75, 0x6d, 0x65, 0x64, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x44, 0x72, 0x69, 0x66, 0x74, 0x32,
	0xa0, 0x05, 0x0a, 0x07, 0x62, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x4c, 0x0a, 0x11, 0x4c,
	0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x41, 0x73, 0x73, 0x65, 0x74, 0x50, 0x61, 0x69, 0x72, 0x73,
	0x12, 0x19, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x41, 0x73, 0x73, 0x65, 0x74, 0x50,
	0x61, 0x69, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x41, 0x6c, 0x6c, 0x41, 0x73, 0x73, 0x65, 0x74, 0x50, 0x61, 0x69, 0x72, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x76, 0x0a, 0x1f, 0x45, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x46, 0x75, 0x74, 0x75, 0x72, 0x65, 0x73, 0x50, 0x65,
	0x72, 0x70, 0x65, 0x74, 0x75, 0x61, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x27, 0x2e, 0x45,
	0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x46, 0x75, 0x74, 0x75, 0x72, 0x65, 0x73,
	0x50, 0x65, 0x72, 0x70, 0x65, 0x74, 0x75, 0x61, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x4e,
	0x65, 0x77, 0x46, 0x75, 0x74, 0x75, 0x72, 0x65, 0x73, 0x50, 0x65, 0x72, 0x70, 0x65, 0x74, 0x75,
	0x61, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x52, 0x0a, 0x13, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x53,
	0x70, 0x6f, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x1b, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x65, 0x4e, 0x65, 0x77, 0x53, 0x70, 0x6f, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x4e,
	0x65, 0x77, 0x53, 0x70, 0x6f, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x74, 0x65,
	0x73, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x16, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x74,
	0x65, 0x73, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x17, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6a, 0x0a, 0x1b, 0x52, 0x65,
	0x61, 0x64, 0x50, 0x65, 0x72, 0x70, 0x65, 0x74, 0x75, 0x61, 0x6c, 0x46, 0x75, 0x74, 0x75, 0x72,
	0x65, 0x73, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x23, 0x2e, 0x52, 0x65, 0x61, 0x64,
	0x50, 0x65, 0x72, 0x70, 0x65, 0x74, 0x75, 0x61, 0x6c, 0x46, 0x75, 0x74, 0x75, 0x72, 0x65, 0x73,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24,
	0x2e, 0x52, 0x65, 0x61, 0x64, 0x50, 0x65, 0x72, 0x70, 0x65, 0x74, 0x75, 0x61, 0x6c, 0x46, 0x75,
	0x74, 0x75, 0x72, 0x65, 0x73, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x46, 0x75, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x52, 0x61, 0x74, 0x65, 0x73, 0x12, 0x17, 0x2e, 0x47, 0x65, 0x74, 0x46,
	0x75, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x18, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x75, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52,
	0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4c,
	0x0a, 0x11, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x61, 0x6c, 0x73, 0x12, 0x19, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x72, 0x65, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61,
	0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x09,
	0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x11, 0x2e, 0x47, 0x65, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x2a, 0x5a, 0x28, 0x73, 0x77, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x74, 0x61, 0x69,
	0x6c, 0x2f, 0x73, 0x2e, 0x62, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x3b, 0x62, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_s_binance_proto_binance_proto_rawDescOnce sync.Once
	file_s_binance_proto_binance_proto_rawDescData = file_s_binance_proto_binance_proto_rawDesc
)

func file_s_binance_proto_binance_proto_rawDescGZIP() []byte {
	file_s_binance_proto_binance_proto_rawDescOnce.Do(func() {
		file_s_binance_proto_binance_proto_rawDescData = protoimpl.X.CompressGZIP(file_s_binance_proto_binance_proto_rawDescData)
	})
	return file_s_binance_proto_binance_proto_rawDescData
}

var file_s_binance_proto_binance_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_s_binance_proto_binance_proto_goTypes = []interface{}{
	(*AssetPair)(nil),                               // 0: AssetPair
	(*ListAllAssetPairsRequest)(nil),                // 1: ListAllAssetPairsRequest
	(*ListAllAssetPairsResponse)(nil),               // 2: ListAllAssetPairsResponse
	(*ExecuteNewFuturesPerpetualOrderRequest)(nil),  // 3: ExecuteNewFuturesPerpetualOrderRequest
	(*ExecuteNewFuturesPerpetualOrderResponse)(nil), // 4: ExecuteNewFuturesPerpetualOrderResponse
	(*ExecuteNewSpotOrderRequest)(nil),              // 5: ExecuteNewSpotOrderRequest
	(*ExecuteNewSpotOrderResponse)(nil),             // 6: ExecuteNewSpotOrderResponse
	(*ReadPerpetualFuturesAccountRequest)(nil),      // 7: ReadPerpetualFuturesAccountRequest
	(*ReadPerpetualFuturesAccountResponse)(nil),     // 8: ReadPerpetualFuturesAccountResponse
	(*GetLatestPriceRequest)(nil),                   // 9: GetLatestPriceRequest
	(*GetLatestPriceResponse)(nil),                  // 10: GetLatestPriceResponse
	(*GetFundingRatesRequest)(nil),                  // 11: GetFundingRatesRequest
	(*FundingRateInfo)(nil),                         // 12: FundingRateInfo
	(*GetFundingRatesResponse)(nil),                 // 13: GetFundingRatesResponse
	(*VerifyCredentialsRequest)(nil),                // 14: VerifyCredentialsRequest
	(*VerifyCredentialsResponse)(nil),               // 15: VerifyCredentialsResponse
	(*GetStatusRequest)(nil),                        // 16: GetStatusRequest
	(*GetStatusResponse)(nil),                       // 17: GetStatusResponse
	(*proto1.Order)(nil),                            // 18: Order
	(*timestamppb.Timestamp)(nil),                   // 19: google.protobuf.Timestamp
	(*proto1.VenueCredentials)(nil),                 // 20: VenueCredentials
}
var file_s_binance_proto_binance_proto_depIdxs = []int32{
	0,  // 0: ListAllAssetPairsResponse.asset_pairs:type_name -> AssetPair
	18, // 1: ExecuteNewFuturesPerpetualOrderRequest.order:type_name -> Order
	19, // 2: ExecuteNewFuturesPerpetualOrderRequest.timestamp:type_name -> google.protobuf.Timestamp
	20, // 3: ExecuteNewFuturesPerpetualOrderRequest.credentials:type_name -> VenueCredentials
	18, // 4: ExecuteNewFuturesPerpetualOrderResponse.order:type_name -> Order
	18, // 5: ExecuteNewSpotOrderRequest.order:type_name -> Order
	19, // 6: ExecuteNewSpotOrderRequest.timestamp:type_name -> google.protobuf.Timestamp
	20, // 7: ExecuteNewSpotOrderRequest.credentials:type_name -> VenueCredentials
	18, // 8: ExecuteNewSpotOrderResponse.order:type_name -> Order
	20, // 9: ReadPerpetualFuturesAccountRequest.credentials:type_name -> VenueCredentials
	19, // 10: ReadPerpetualFuturesAccountResponse.last_updated:type_name -> google.protobuf.Timestamp
	12, // 11: GetFundingRatesResponse.funding_rates:type_name -> FundingRateInfo
	20, // 12: VerifyCredentialsRequest.credentials:type_name -> VenueCredentials
	1,  // 13: binance.ListAllAssetPairs:input_type -> ListAllAssetPairsRequest
	3,  // 14: binance.ExecuteNewFuturesPerpetualOrder:input_type -> ExecuteNewFuturesPerpetualOrderRequest
	5,  // 15: binance.ExecuteNewSpotOrder:input_type -> ExecuteNewSpotOrderRequest
	9,  // 16: binance.GetLatestPrice:input_type -> GetLatestPriceRequest
	7,  // 17: binance.ReadPerpetualFuturesAccount:input_type -> ReadPerpetualFuturesAccountRequest
	11, // 18: binance.GetFundingRates:input_type -> GetFundingRatesRequest
	14, // 19: binance.VerifyCredentials:input_type -> VerifyCredentialsRequest
	16, // 20: binance.GetStatus:input_type -> GetStatusRequest
	2,  // 21: binance.ListAllAssetPairs:output_type -> ListAllAssetPairsResponse
	4,  // 22: binance.ExecuteNewFuturesPerpetualOrder:output_type -> ExecuteNewFuturesPerpetualOrderResponse
	6,  // 23: binance.ExecuteNewSpotOrder:output_type -> ExecuteNewSpotOrderResponse
	10, // 24: binance.GetLatestPrice:output_type -> GetLatestPriceResponse
	8,  // 25: binance.ReadPerpetualFuturesAccount:output_type -> ReadPerpetualFuturesAccountResponse
	13, // 26: binance.GetFundingRates:output_type -> GetFundingRatesResponse
	15, // 27: binance.VerifyCredentials:output_type -> VerifyCredentialsResponse
	17, // 28: binance.GetStatus:output_type -> GetStatusResponse
	21, // [21:29] is the sub-list for method output_type
	13, // [13:21] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_s_binance_proto_binance_proto_init() }
func file_s_binance_proto_binance_proto_init() {
	if File_s_binance_proto_binance_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_s_binance_proto_binance_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssetPair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_binance_proto_binance_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAllAssetPairsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_binance_proto_binance_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAllAssetPairsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_binance_proto_binance_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteNewFuturesPerpetualOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_binance_proto_binance_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteNewFuturesPerpetualOrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_binance_proto_binance_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteNewSpotOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_binance_proto_binance_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteNewSpotOrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_binance_proto_binance_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadPerpetualFuturesAccountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_binance_proto_binance_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadPerpetualFuturesAccountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_binance_proto_binance_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLatestPriceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_binance_proto_binance_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLatestPriceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_binance_proto_binance_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFundingRatesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_binance_proto_binance_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FundingRateInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_binance_proto_binance_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFundingRatesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_binance_proto_binance_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyCredentialsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_binance_proto_binance_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyCredentialsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_binance_proto_binance_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_binance_proto_binance_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_s_binance_proto_binance_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_s_binance_proto_binance_proto_goTypes,
		DependencyIndexes: file_s_binance_proto_binance_proto_depIdxs,
		MessageInfos:      file_s_binance_proto_binance_proto_msgTypes,
	}.Build()
	File_s_binance_proto_binance_proto = out.File
	file_s_binance_proto_binance_proto_rawDesc = nil
	file_s_binance_proto_binance_proto_goTypes = nil
	file_s_binance_proto_binance_proto_depIdxs = nil
}
