version: "3.9"

volumes:
  swallowtail_zookeeper_data: {}
  swallowtail_zookeeper_datalog: {}
  swallowtail_kafka_data: {}

services:
  ### --- APIs --- ###

  ### --- Backend --- ###
  swallowtail.s.account:
    hostname: swallowtail-s-account
    image: swallowtail.s.account
    ports:
      - "8001:8000"
    env_file:
      - .envs/postgres.env
    depends_on:
      - postgres
    profiles:
      - backend

  swallowtail.s.discord:
    hostname: swallowtail-s-discord
    image: swallowtail.s.discord
    ports:
      - "8002:8000"
    env_file:
      - .envs/postgres.env
      - .envs/discord.env
    depends_on:
      - postgres
    profiles:
      - backend

  swallowtail.s.satoshi:
    hostname: swallowtail-s-satoshi
    image: swallowtail.s.satoshi
    ports:
      - "8003:8000"
    env_file:
      - .envs/postgres.env
      - .envs/discord.env
      - .envs/twitter.env
    depends_on:
      - postgres
      - swallowtail.s.binance
      - swallowtail.s.ftx
    profiles:
      - backend

  swallowtail.s.googlesheets:
    hostname: swallowtail-s-googlesheets
    image: swallowtail.s.googlesheets
    ports:
      - "8004:8000"
    env_file:
      - .envs/postgres.env
    depends_on:
      - postgres
    profiles:
      - backend

  swallowtail.s.binance:
    hostname: swallowtail-s-binance
    image: swallowtail.s.binance
    ports:
      - "8005:8000"
    env_file:
      - .envs/postgres.env
      - .envs/binance.env
    depends_on:
      - postgres
    profiles:
      - backend

  swallowtail.s.coingecko:
    hostname: swallowtail-s-coingecko
    image: swallowtail.s.coingecko
    ports:
      - "8006:8000"
    depends_on:
      - postgres
    profiles:
      - backend

  swallowtail.s.payments:
    hostname: swallowtail-s-payments
    image: swallowtail.s.payments
    ports:
      - "8007:8000"
    env_file:
      - .envs/postgres.env
    depends_on:
      - postgres
    profiles:
      - backend

  swallowtail.s.ftx:
    hostname: swallowtail-s-ftx
    image: swallowtail.s.ftx
    ports:
      - "8008:8000"
    env_file:
      - .envs/ftx.env
    depends_on:
      - postgres
    profiles:
      - backend

  swallowtail.s.tradeengine:
    hostname: swallowtail-s-tradeengine
    image: swallowtail.s.tradeengine
    ports:
      - "8009:8000"
    env_file:
      - .envs/postgres.env
    depends_on:
      - postgres
    profiles:
      - backend

  swallowtail.s.marketdata:
    hostname: swallowtail-s-marketdata
    image: swallowtail.s.marketdata
    ports:
      - "8010:8000"
    env_file:
      - .envs/postgres.env
    depends_on:
      - postgres
    profiles:
      - backend

  swallowtail.s.bitfinex:
    hostname: swallowtail-s-bitfinex
    image: swallowtail.s.bitfinex
    ports:
      - "8011:8000"
    env_file:
      - .envs/postgres.env
    depends_on:
      - postgres
    profiles:
      - backend

  swallowtail.s.solananfts:
    hostname: swallowtail-s-solananfts
    image: swallowtail.s.solananfts
    ports:
      - "8012:8000"
    env_file:
      - .envs/postgres.env
    depends_on:
      - postgres
    profiles:
      - backend

  ### -- Crons --- ###

  swallowtail.c.payments:
    hostname: swallowtail-c-payments
    image: swallowtail.c.payments
    depends_on:
      - swallowtail.s.payments
    profiles:
      - backend

  swallowtail.c.venues:
    hostname: swallowtail-c-venues
    image: swallowtail.c.venues
    depends_on:
      - swallowtail.s.binance
      - swallowtail.s.bitfinex
      - swallowtail.s.ftx
    profiles:
      - backend

  swallowtail.c.satoshi:
    hostname: swallowtail-c-satoshi
    image: swallowtail.c.satoshi
    profiles:
      - backend

  swallowtail.c.marketdata:
    hostname: swallowtail-c-marketdata
    image: swallowtail.c.marketdata
    profiles:
      - backend

  ### --- Infrastructure --- ###

  ## -- Kafka -- ##
  zookeeper:
    build:
      context: .
      dockerfile: ./infrastructure/zookeeper/Dockerfile
    container_name: swallowtail_zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    profiles:
      - backend
      - kafka-cluster

  kafka_1:
    build:
      context: .
      dockerfile: ./infrastructure/kafka/Dockerfile
    container_name: swallowtail_kafka_1
    ports: 
      - "9093:9093"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=swallowtail_zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://swallowtail_kafka_1:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
    profiles:
      - backend
      - kafka-cluster

  kafka_2:
    build:
      context: .
      dockerfile: ./infrastructure/kafka/Dockerfile
    container_name: swallowtail_kafka_2
    ports: 
      - "9094:9094"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=swallowtail_zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://swallowtail_kafka_2:9092,EXTERNAL://localhost:9094
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
    profiles:
      - backend
      - kafka-cluster

  kafka_3:
    build:
      context: .
      dockerfile: ./infrastructure/kafka/Dockerfile
    container_name: swallowtail_kafka_3
    ports: 
      - "9095:9095"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=swallowtail_zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9095
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://swallowtail_kafka_3:9092,EXTERNAL://localhost:9095
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
    profiles:
      - backend
      - kafka-cluster

  kafdrop:
    build:
      context: .
      dockerfile: ./infrastructure/kafdrop/Dockerfile
    ports:
      - "9000:9000"
    environment:
      - KAFKA_BROKERCONNECT=swallowtail_kafka_1:9092,swallowtail_kafka_2:9092,swallowtail_kafka_3:9092
    depends_on:
      - kafka_1
    profiles:
      - backend
      - kafka-cluster

  ## -- Postgres -- ##
  postgres:
    build:
      context: .
      dockerfile: ./infrastructure/postgres/Dockerfile
    image: i.swallowtail.postgres 
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=swallowtail
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    profiles:
      - backend
