// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.17.3
// source: s.googlesheets/proto/googlesheets.proto

package googlesheetsproto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CreatePortfolioSheetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId              string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email               string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	ShouldShare         bool   `protobuf:"varint,3,opt,name=shouldShare,proto3" json:"shouldShare,omitempty"`
	Active              bool   `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	ShouldPagerOnError  bool   `protobuf:"varint,5,opt,name=should_pager_on_error,json=shouldPagerOnError,proto3" json:"should_pager_on_error,omitempty"`
	ShouldPagerOnTarget bool   `protobuf:"varint,6,opt,name=should_pager_on_target,json=shouldPagerOnTarget,proto3" json:"should_pager_on_target,omitempty"`
}

func (x *CreatePortfolioSheetRequest) Reset() {
	*x = CreatePortfolioSheetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_googlesheets_proto_googlesheets_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePortfolioSheetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePortfolioSheetRequest) ProtoMessage() {}

func (x *CreatePortfolioSheetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_s_googlesheets_proto_googlesheets_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePortfolioSheetRequest.ProtoReflect.Descriptor instead.
func (*CreatePortfolioSheetRequest) Descriptor() ([]byte, []int) {
	return file_s_googlesheets_proto_googlesheets_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePortfolioSheetRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreatePortfolioSheetRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreatePortfolioSheetRequest) GetShouldShare() bool {
	if x != nil {
		return x.ShouldShare
	}
	return false
}

func (x *CreatePortfolioSheetRequest) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *CreatePortfolioSheetRequest) GetShouldPagerOnError() bool {
	if x != nil {
		return x.ShouldPagerOnError
	}
	return false
}

func (x *CreatePortfolioSheetRequest) GetShouldPagerOnTarget() bool {
	if x != nil {
		return x.ShouldPagerOnTarget
	}
	return false
}

type CreatePortfolioSheetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	URL string `protobuf:"bytes,1,opt,name=URL,proto3" json:"URL,omitempty"`
}

func (x *CreatePortfolioSheetResponse) Reset() {
	*x = CreatePortfolioSheetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_googlesheets_proto_googlesheets_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePortfolioSheetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePortfolioSheetResponse) ProtoMessage() {}

func (x *CreatePortfolioSheetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_s_googlesheets_proto_googlesheets_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePortfolioSheetResponse.ProtoReflect.Descriptor instead.
func (*CreatePortfolioSheetResponse) Descriptor() ([]byte, []int) {
	return file_s_googlesheets_proto_googlesheets_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePortfolioSheetResponse) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

type RegisterNewPortfolioSheetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId          string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GooglesheetsUrl string `protobuf:"bytes,2,opt,name=googlesheets_url,json=googlesheetsUrl,proto3" json:"googlesheets_url,omitempty"`
}

func (x *RegisterNewPortfolioSheetRequest) Reset() {
	*x = RegisterNewPortfolioSheetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_googlesheets_proto_googlesheets_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterNewPortfolioSheetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNewPortfolioSheetRequest) ProtoMessage() {}

func (x *RegisterNewPortfolioSheetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_s_googlesheets_proto_googlesheets_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNewPortfolioSheetRequest.ProtoReflect.Descriptor instead.
func (*RegisterNewPortfolioSheetRequest) Descriptor() ([]byte, []int) {
	return file_s_googlesheets_proto_googlesheets_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterNewPortfolioSheetRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterNewPortfolioSheetRequest) GetGooglesheetsUrl() string {
	if x != nil {
		return x.GooglesheetsUrl
	}
	return ""
}

type RegisterNewPortfolioSheetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegisterNewPortfolioSheetResponse) Reset() {
	*x = RegisterNewPortfolioSheetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_googlesheets_proto_googlesheets_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterNewPortfolioSheetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNewPortfolioSheetResponse) ProtoMessage() {}

func (x *RegisterNewPortfolioSheetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_s_googlesheets_proto_googlesheets_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNewPortfolioSheetResponse.ProtoReflect.Descriptor instead.
func (*RegisterNewPortfolioSheetResponse) Descriptor() ([]byte, []int) {
	return file_s_googlesheets_proto_googlesheets_proto_rawDescGZIP(), []int{3}
}

var File_s_googlesheets_proto_googlesheets_proto protoreflect.FileDescriptor

var file_s_googlesheets_proto_googlesheets_proto_rawDesc = []byte{
	0x0a, 0x27, 0x73, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x73, 0x68, 0x65, 0x65, 0x74, 0x73,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x73, 0x68, 0x65,
	0x65, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xee, 0x01, 0x0a, 0x1b, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x53, 0x68, 0x65,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x68, 0x6f, 0x75,
	0x6c, 0x64, 0x53, 0x68, 0x61, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x73,
	0x68, 0x6f, 0x75, 0x6c, 0x64, 0x53, 0x68, 0x61, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x12, 0x31, 0x0a, 0x15, 0x73, 0x68, 0x6f, 0x75, 0x6c, 0x64, 0x5f, 0x70, 0x61, 0x67,
	0x65, 0x72, 0x5f, 0x6f, 0x6e, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x12, 0x73, 0x68, 0x6f, 0x75, 0x6c, 0x64, 0x50, 0x61, 0x67, 0x65, 0x72, 0x4f, 0x6e,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x33, 0x0a, 0x16, 0x73, 0x68, 0x6f, 0x75, 0x6c, 0x64, 0x5f,
	0x70, 0x61, 0x67, 0x65, 0x72, 0x5f, 0x6f, 0x6e, 0x5f, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x13, 0x73, 0x68, 0x6f, 0x75, 0x6c, 0x64, 0x50, 0x61, 0x67,
	0x65, 0x72, 0x4f, 0x6e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x22, 0x30, 0x0a, 0x1c, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x53, 0x68, 0x65,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x52,
	0x4c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x52, 0x4c, 0x22, 0x66, 0x0a, 0x20,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x65, 0x77, 0x50, 0x6f, 0x72, 0x74, 0x66,
	0x6f, 0x6c, 0x69, 0x6f, 0x53, 0x68, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x10, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x73, 0x68, 0x65, 0x65, 0x74, 0x73, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x73, 0x68, 0x65, 0x65, 0x74,
	0x73, 0x55, 0x72, 0x6c, 0x22, 0x23, 0x0a, 0x21, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x4e, 0x65, 0x77, 0x50, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x53, 0x68, 0x65, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xcb, 0x01, 0x0a, 0x0c, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x73, 0x68, 0x65, 0x65, 0x74, 0x73, 0x12, 0x55, 0x0a, 0x14, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x53, 0x68, 0x65,
	0x65, 0x74, 0x12, 0x1c, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x66,
	0x6f, 0x6c, 0x69, 0x6f, 0x53, 0x68, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c,
	0x69, 0x6f, 0x53, 0x68, 0x65, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x64, 0x0a, 0x19, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x65, 0x77,
	0x50, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x53, 0x68, 0x65, 0x65, 0x74, 0x12, 0x21,
	0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x65, 0x77, 0x50, 0x6f, 0x72, 0x74,
	0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x53, 0x68, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x22, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x65, 0x77, 0x50,
	0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x53, 0x68, 0x65, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x16, 0x5a, 0x14, 0x2e, 0x2f, 0x3b, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x73, 0x68, 0x65, 0x65, 0x74, 0x73, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_s_googlesheets_proto_googlesheets_proto_rawDescOnce sync.Once
	file_s_googlesheets_proto_googlesheets_proto_rawDescData = file_s_googlesheets_proto_googlesheets_proto_rawDesc
)

func file_s_googlesheets_proto_googlesheets_proto_rawDescGZIP() []byte {
	file_s_googlesheets_proto_googlesheets_proto_rawDescOnce.Do(func() {
		file_s_googlesheets_proto_googlesheets_proto_rawDescData = protoimpl.X.CompressGZIP(file_s_googlesheets_proto_googlesheets_proto_rawDescData)
	})
	return file_s_googlesheets_proto_googlesheets_proto_rawDescData
}

var file_s_googlesheets_proto_googlesheets_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_s_googlesheets_proto_googlesheets_proto_goTypes = []interface{}{
	(*CreatePortfolioSheetRequest)(nil),       // 0: CreatePortfolioSheetRequest
	(*CreatePortfolioSheetResponse)(nil),      // 1: CreatePortfolioSheetResponse
	(*RegisterNewPortfolioSheetRequest)(nil),  // 2: RegisterNewPortfolioSheetRequest
	(*RegisterNewPortfolioSheetResponse)(nil), // 3: RegisterNewPortfolioSheetResponse
}
var file_s_googlesheets_proto_googlesheets_proto_depIdxs = []int32{
	0, // 0: googlesheets.CreatePortfolioSheet:input_type -> CreatePortfolioSheetRequest
	2, // 1: googlesheets.RegisterNewPortfolioSheet:input_type -> RegisterNewPortfolioSheetRequest
	1, // 2: googlesheets.CreatePortfolioSheet:output_type -> CreatePortfolioSheetResponse
	3, // 3: googlesheets.RegisterNewPortfolioSheet:output_type -> RegisterNewPortfolioSheetResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_s_googlesheets_proto_googlesheets_proto_init() }
func file_s_googlesheets_proto_googlesheets_proto_init() {
	if File_s_googlesheets_proto_googlesheets_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_s_googlesheets_proto_googlesheets_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePortfolioSheetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_googlesheets_proto_googlesheets_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePortfolioSheetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_googlesheets_proto_googlesheets_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterNewPortfolioSheetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_googlesheets_proto_googlesheets_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterNewPortfolioSheetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_s_googlesheets_proto_googlesheets_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_s_googlesheets_proto_googlesheets_proto_goTypes,
		DependencyIndexes: file_s_googlesheets_proto_googlesheets_proto_depIdxs,
		MessageInfos:      file_s_googlesheets_proto_googlesheets_proto_msgTypes,
	}.Build()
	File_s_googlesheets_proto_googlesheets_proto = out.File
	file_s_googlesheets_proto_googlesheets_proto_rawDesc = nil
	file_s_googlesheets_proto_googlesheets_proto_goTypes = nil
	file_s_googlesheets_proto_googlesheets_proto_depIdxs = nil
}
