// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package tradeengineproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TradeengineClient is the client API for Tradeengine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TradeengineClient interface {
	CreateTrade(ctx context.Context, in *CreateTradeRequest, opts ...grpc.CallOption) (*CreateTradeResponse, error)
	AddParticipantToTrade(ctx context.Context, in *AddParticipantToTradeRequest, opts ...grpc.CallOption) (*AddParticipantToTradeResponse, error)
	ReadTradeByTradeID(ctx context.Context, in *ReadTradeByTradeIDRequest, opts ...grpc.CallOption) (*ReadTradeByTradeIDResponse, error)
}

type tradeengineClient struct {
	cc grpc.ClientConnInterface
}

func NewTradeengineClient(cc grpc.ClientConnInterface) TradeengineClient {
	return &tradeengineClient{cc}
}

func (c *tradeengineClient) CreateTrade(ctx context.Context, in *CreateTradeRequest, opts ...grpc.CallOption) (*CreateTradeResponse, error) {
	out := new(CreateTradeResponse)
	err := c.cc.Invoke(ctx, "/tradeengine/CreateTrade", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeengineClient) AddParticipantToTrade(ctx context.Context, in *AddParticipantToTradeRequest, opts ...grpc.CallOption) (*AddParticipantToTradeResponse, error) {
	out := new(AddParticipantToTradeResponse)
	err := c.cc.Invoke(ctx, "/tradeengine/AddParticipantToTrade", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeengineClient) ReadTradeByTradeID(ctx context.Context, in *ReadTradeByTradeIDRequest, opts ...grpc.CallOption) (*ReadTradeByTradeIDResponse, error) {
	out := new(ReadTradeByTradeIDResponse)
	err := c.cc.Invoke(ctx, "/tradeengine/ReadTradeByTradeID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TradeengineServer is the server API for Tradeengine service.
// All implementations must embed UnimplementedTradeengineServer
// for forward compatibility
type TradeengineServer interface {
	CreateTrade(context.Context, *CreateTradeRequest) (*CreateTradeResponse, error)
	AddParticipantToTrade(context.Context, *AddParticipantToTradeRequest) (*AddParticipantToTradeResponse, error)
	ReadTradeByTradeID(context.Context, *ReadTradeByTradeIDRequest) (*ReadTradeByTradeIDResponse, error)
	mustEmbedUnimplementedTradeengineServer()
}

// UnimplementedTradeengineServer must be embedded to have forward compatible implementations.
type UnimplementedTradeengineServer struct {
}

func (*UnimplementedTradeengineServer) CreateTrade(context.Context, *CreateTradeRequest) (*CreateTradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTrade not implemented")
}
func (*UnimplementedTradeengineServer) AddParticipantToTrade(context.Context, *AddParticipantToTradeRequest) (*AddParticipantToTradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddParticipantToTrade not implemented")
}
func (*UnimplementedTradeengineServer) ReadTradeByTradeID(context.Context, *ReadTradeByTradeIDRequest) (*ReadTradeByTradeIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadTradeByTradeID not implemented")
}
func (*UnimplementedTradeengineServer) mustEmbedUnimplementedTradeengineServer() {}

func RegisterTradeengineServer(s *grpc.Server, srv TradeengineServer) {
	s.RegisterService(&_Tradeengine_serviceDesc, srv)
}

func _Tradeengine_CreateTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeengineServer).CreateTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tradeengine/CreateTrade",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeengineServer).CreateTrade(ctx, req.(*CreateTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tradeengine_AddParticipantToTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddParticipantToTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeengineServer).AddParticipantToTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tradeengine/AddParticipantToTrade",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeengineServer).AddParticipantToTrade(ctx, req.(*AddParticipantToTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tradeengine_ReadTradeByTradeID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadTradeByTradeIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeengineServer).ReadTradeByTradeID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tradeengine/ReadTradeByTradeID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeengineServer).ReadTradeByTradeID(ctx, req.(*ReadTradeByTradeIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Tradeengine_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tradeengine",
	HandlerType: (*TradeengineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTrade",
			Handler:    _Tradeengine_CreateTrade_Handler,
		},
		{
			MethodName: "AddParticipantToTrade",
			Handler:    _Tradeengine_AddParticipantToTrade_Handler,
		},
		{
			MethodName: "ReadTradeByTradeID",
			Handler:    _Tradeengine_ReadTradeByTradeID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "s.trade-engine/proto/tradeengine.proto",
}
