// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.17.3
// source: s.market-data/proto/marketdata.proto

package marketdataproto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PublishLatestPriceInformationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PublishLatestPriceInformationRequest) Reset() {
	*x = PublishLatestPriceInformationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_market_data_proto_marketdata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishLatestPriceInformationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishLatestPriceInformationRequest) ProtoMessage() {}

func (x *PublishLatestPriceInformationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_s_market_data_proto_marketdata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishLatestPriceInformationRequest.ProtoReflect.Descriptor instead.
func (*PublishLatestPriceInformationRequest) Descriptor() ([]byte, []int) {
	return file_s_market_data_proto_marketdata_proto_rawDescGZIP(), []int{0}
}

type PublishLatestPriceInformationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PublishLatestPriceInformationResponse) Reset() {
	*x = PublishLatestPriceInformationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_market_data_proto_marketdata_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishLatestPriceInformationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishLatestPriceInformationResponse) ProtoMessage() {}

func (x *PublishLatestPriceInformationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_s_market_data_proto_marketdata_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishLatestPriceInformationResponse.ProtoReflect.Descriptor instead.
func (*PublishLatestPriceInformationResponse) Descriptor() ([]byte, []int) {
	return file_s_market_data_proto_marketdata_proto_rawDescGZIP(), []int{1}
}

type PublishVolatilityInformationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PublishVolatilityInformationRequest) Reset() {
	*x = PublishVolatilityInformationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_market_data_proto_marketdata_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishVolatilityInformationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishVolatilityInformationRequest) ProtoMessage() {}

func (x *PublishVolatilityInformationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_s_market_data_proto_marketdata_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishVolatilityInformationRequest.ProtoReflect.Descriptor instead.
func (*PublishVolatilityInformationRequest) Descriptor() ([]byte, []int) {
	return file_s_market_data_proto_marketdata_proto_rawDescGZIP(), []int{2}
}

type PublishVolatilityInformationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PublishVolatilityInformationResponse) Reset() {
	*x = PublishVolatilityInformationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_market_data_proto_marketdata_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishVolatilityInformationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishVolatilityInformationResponse) ProtoMessage() {}

func (x *PublishVolatilityInformationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_s_market_data_proto_marketdata_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishVolatilityInformationResponse.ProtoReflect.Descriptor instead.
func (*PublishVolatilityInformationResponse) Descriptor() ([]byte, []int) {
	return file_s_market_data_proto_marketdata_proto_rawDescGZIP(), []int{3}
}

type PublishATHInformationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PublishATHInformationRequest) Reset() {
	*x = PublishATHInformationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_market_data_proto_marketdata_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishATHInformationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishATHInformationRequest) ProtoMessage() {}

func (x *PublishATHInformationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_s_market_data_proto_marketdata_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishATHInformationRequest.ProtoReflect.Descriptor instead.
func (*PublishATHInformationRequest) Descriptor() ([]byte, []int) {
	return file_s_market_data_proto_marketdata_proto_rawDescGZIP(), []int{4}
}

type PublishATHInformationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PublishATHInformationResponse) Reset() {
	*x = PublishATHInformationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_market_data_proto_marketdata_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishATHInformationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishATHInformationResponse) ProtoMessage() {}

func (x *PublishATHInformationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_s_market_data_proto_marketdata_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishATHInformationResponse.ProtoReflect.Descriptor instead.
func (*PublishATHInformationResponse) Descriptor() ([]byte, []int) {
	return file_s_market_data_proto_marketdata_proto_rawDescGZIP(), []int{5}
}

type PublishFundingRatesInformationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PublishFundingRatesInformationRequest) Reset() {
	*x = PublishFundingRatesInformationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_market_data_proto_marketdata_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishFundingRatesInformationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishFundingRatesInformationRequest) ProtoMessage() {}

func (x *PublishFundingRatesInformationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_s_market_data_proto_marketdata_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishFundingRatesInformationRequest.ProtoReflect.Descriptor instead.
func (*PublishFundingRatesInformationRequest) Descriptor() ([]byte, []int) {
	return file_s_market_data_proto_marketdata_proto_rawDescGZIP(), []int{6}
}

type PublishFundingRatesInformationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PublishFundingRatesInformationResponse) Reset() {
	*x = PublishFundingRatesInformationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_market_data_proto_marketdata_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishFundingRatesInformationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishFundingRatesInformationResponse) ProtoMessage() {}

func (x *PublishFundingRatesInformationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_s_market_data_proto_marketdata_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishFundingRatesInformationResponse.ProtoReflect.Descriptor instead.
func (*PublishFundingRatesInformationResponse) Descriptor() ([]byte, []int) {
	return file_s_market_data_proto_marketdata_proto_rawDescGZIP(), []int{7}
}

type PublishSolanaNFTPriceInformationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PublishSolanaNFTPriceInformationRequest) Reset() {
	*x = PublishSolanaNFTPriceInformationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_market_data_proto_marketdata_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishSolanaNFTPriceInformationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishSolanaNFTPriceInformationRequest) ProtoMessage() {}

func (x *PublishSolanaNFTPriceInformationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_s_market_data_proto_marketdata_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishSolanaNFTPriceInformationRequest.ProtoReflect.Descriptor instead.
func (*PublishSolanaNFTPriceInformationRequest) Descriptor() ([]byte, []int) {
	return file_s_market_data_proto_marketdata_proto_rawDescGZIP(), []int{8}
}

type PublishSolanaNFTPriceInformationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PublishSolanaNFTPriceInformationResponse) Reset() {
	*x = PublishSolanaNFTPriceInformationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_market_data_proto_marketdata_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishSolanaNFTPriceInformationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishSolanaNFTPriceInformationResponse) ProtoMessage() {}

func (x *PublishSolanaNFTPriceInformationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_s_market_data_proto_marketdata_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishSolanaNFTPriceInformationResponse.ProtoReflect.Descriptor instead.
func (*PublishSolanaNFTPriceInformationResponse) Descriptor() ([]byte, []int) {
	return file_s_market_data_proto_marketdata_proto_rawDescGZIP(), []int{9}
}

var File_s_market_data_proto_marketdata_proto protoreflect.FileDescriptor

var file_s_market_data_proto_marketdata_proto_rawDesc = []byte{
	0x0a, 0x24, 0x73, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2d, 0x64, 0x61, 0x74, 0x61, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x26, 0x0a, 0x24, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73,
	0x68, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x27,
	0x0a, 0x25, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x25, 0x0a, 0x23, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x56, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x26,
	0x0a, 0x24, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x56, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6c,
	0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1e, 0x0a, 0x1c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73,
	0x68, 0x41, 0x54, 0x48, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1f, 0x0a, 0x1d, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73,
	0x68, 0x41, 0x54, 0x48, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x27, 0x0a, 0x25, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x46, 0x75, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x61, 0x74, 0x65, 0x73, 0x49, 0x6e,
	0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x28, 0x0a, 0x26, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x46, 0x75, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x52, 0x61, 0x74, 0x65, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x29, 0x0a, 0x27, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x73, 0x68, 0x53, 0x6f, 0x6c, 0x61, 0x6e, 0x61, 0x4e, 0x46, 0x54, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2a, 0x0a, 0x28, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68,
	0x53, 0x6f, 0x6c, 0x61, 0x6e, 0x61, 0x4e, 0x46, 0x54, 0x50, 0x72, 0x69, 0x63, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x32, 0xb7, 0x04, 0x0a, 0x0a, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x70, 0x0a, 0x1d, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x4c, 0x61, 0x74, 0x65, 0x73,
	0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x25, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x4c, 0x61, 0x74, 0x65, 0x73,
	0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x6d, 0x0a, 0x1c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x56, 0x6f, 0x6c,
	0x61, 0x74, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x24, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x56, 0x6f, 0x6c, 0x61,
	0x74, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x56, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x58, 0x0a, 0x15, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x41, 0x54, 0x48, 0x49,
	0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x2e, 0x50, 0x75, 0x62,
	0x6c, 0x69, 0x73, 0x68, 0x41, 0x54, 0x48, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x73, 0x68, 0x41, 0x54, 0x48, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x73, 0x0a, 0x1e, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x46, 0x75, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x61, 0x74,
	0x65, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x2e,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x46, 0x75, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x61,
	0x74, 0x65, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x46,
	0x75, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x61, 0x74, 0x65, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x79, 0x0a, 0x20, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x53, 0x6f, 0x6c, 0x61, 0x6e,
	0x61, 0x4e, 0x46, 0x54, 0x50, 0x72, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x53, 0x6f,
	0x6c, 0x61, 0x6e, 0x61, 0x4e, 0x46, 0x54, 0x50, 0x72, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29,
	0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x53, 0x6f, 0x6c, 0x61, 0x6e, 0x61, 0x4e, 0x46,
	0x54, 0x50, 0x72, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x14, 0x5a, 0x12, 0x2e,
	0x2f, 0x3b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x64, 0x61, 0x74, 0x61, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_s_market_data_proto_marketdata_proto_rawDescOnce sync.Once
	file_s_market_data_proto_marketdata_proto_rawDescData = file_s_market_data_proto_marketdata_proto_rawDesc
)

func file_s_market_data_proto_marketdata_proto_rawDescGZIP() []byte {
	file_s_market_data_proto_marketdata_proto_rawDescOnce.Do(func() {
		file_s_market_data_proto_marketdata_proto_rawDescData = protoimpl.X.CompressGZIP(file_s_market_data_proto_marketdata_proto_rawDescData)
	})
	return file_s_market_data_proto_marketdata_proto_rawDescData
}

var file_s_market_data_proto_marketdata_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_s_market_data_proto_marketdata_proto_goTypes = []interface{}{
	(*PublishLatestPriceInformationRequest)(nil),     // 0: PublishLatestPriceInformationRequest
	(*PublishLatestPriceInformationResponse)(nil),    // 1: PublishLatestPriceInformationResponse
	(*PublishVolatilityInformationRequest)(nil),      // 2: PublishVolatilityInformationRequest
	(*PublishVolatilityInformationResponse)(nil),     // 3: PublishVolatilityInformationResponse
	(*PublishATHInformationRequest)(nil),             // 4: PublishATHInformationRequest
	(*PublishATHInformationResponse)(nil),            // 5: PublishATHInformationResponse
	(*PublishFundingRatesInformationRequest)(nil),    // 6: PublishFundingRatesInformationRequest
	(*PublishFundingRatesInformationResponse)(nil),   // 7: PublishFundingRatesInformationResponse
	(*PublishSolanaNFTPriceInformationRequest)(nil),  // 8: PublishSolanaNFTPriceInformationRequest
	(*PublishSolanaNFTPriceInformationResponse)(nil), // 9: PublishSolanaNFTPriceInformationResponse
}
var file_s_market_data_proto_marketdata_proto_depIdxs = []int32{
	0, // 0: marketdata.PublishLatestPriceInformation:input_type -> PublishLatestPriceInformationRequest
	2, // 1: marketdata.PublishVolatilityInformation:input_type -> PublishVolatilityInformationRequest
	4, // 2: marketdata.PublishATHInformation:input_type -> PublishATHInformationRequest
	6, // 3: marketdata.PublishFundingRatesInformation:input_type -> PublishFundingRatesInformationRequest
	8, // 4: marketdata.PublishSolanaNFTPriceInformation:input_type -> PublishSolanaNFTPriceInformationRequest
	1, // 5: marketdata.PublishLatestPriceInformation:output_type -> PublishLatestPriceInformationResponse
	3, // 6: marketdata.PublishVolatilityInformation:output_type -> PublishVolatilityInformationResponse
	5, // 7: marketdata.PublishATHInformation:output_type -> PublishATHInformationResponse
	7, // 8: marketdata.PublishFundingRatesInformation:output_type -> PublishFundingRatesInformationResponse
	9, // 9: marketdata.PublishSolanaNFTPriceInformation:output_type -> PublishSolanaNFTPriceInformationResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_s_market_data_proto_marketdata_proto_init() }
func file_s_market_data_proto_marketdata_proto_init() {
	if File_s_market_data_proto_marketdata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_s_market_data_proto_marketdata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishLatestPriceInformationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_market_data_proto_marketdata_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishLatestPriceInformationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_market_data_proto_marketdata_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishVolatilityInformationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_market_data_proto_marketdata_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishVolatilityInformationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_market_data_proto_marketdata_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishATHInformationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_market_data_proto_marketdata_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishATHInformationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_market_data_proto_marketdata_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishFundingRatesInformationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_market_data_proto_marketdata_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishFundingRatesInformationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_market_data_proto_marketdata_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishSolanaNFTPriceInformationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_market_data_proto_marketdata_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishSolanaNFTPriceInformationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_s_market_data_proto_marketdata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_s_market_data_proto_marketdata_proto_goTypes,
		DependencyIndexes: file_s_market_data_proto_marketdata_proto_depIdxs,
		MessageInfos:      file_s_market_data_proto_marketdata_proto_msgTypes,
	}.Build()
	File_s_market_data_proto_marketdata_proto = out.File
	file_s_market_data_proto_marketdata_proto_rawDesc = nil
	file_s_market_data_proto_marketdata_proto_goTypes = nil
	file_s_market_data_proto_marketdata_proto_depIdxs = nil
}
