// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package marketdataproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MarketdataClient is the client API for Marketdata service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MarketdataClient interface {
	GetExchangeFundingRates(ctx context.Context, in *GetExchangeFundingRatesRequest, opts ...grpc.CallOption) (*GetExchangeFundingRatesResponse, error)
	PublishLatestPriceInformation(ctx context.Context, in *PublishLatestPriceInformationRequest, opts ...grpc.CallOption) (*PublishLatestPriceInformationResponse, error)
	PublishVolatilityInformation(ctx context.Context, in *PublishVolatilityInformationRequest, opts ...grpc.CallOption) (*PublishVolatilityInformationResponse, error)
}

type marketdataClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketdataClient(cc grpc.ClientConnInterface) MarketdataClient {
	return &marketdataClient{cc}
}

func (c *marketdataClient) GetExchangeFundingRates(ctx context.Context, in *GetExchangeFundingRatesRequest, opts ...grpc.CallOption) (*GetExchangeFundingRatesResponse, error) {
	out := new(GetExchangeFundingRatesResponse)
	err := c.cc.Invoke(ctx, "/marketdata/GetExchangeFundingRates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketdataClient) PublishLatestPriceInformation(ctx context.Context, in *PublishLatestPriceInformationRequest, opts ...grpc.CallOption) (*PublishLatestPriceInformationResponse, error) {
	out := new(PublishLatestPriceInformationResponse)
	err := c.cc.Invoke(ctx, "/marketdata/PublishLatestPriceInformation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketdataClient) PublishVolatilityInformation(ctx context.Context, in *PublishVolatilityInformationRequest, opts ...grpc.CallOption) (*PublishVolatilityInformationResponse, error) {
	out := new(PublishVolatilityInformationResponse)
	err := c.cc.Invoke(ctx, "/marketdata/PublishVolatilityInformation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketdataServer is the server API for Marketdata service.
// All implementations must embed UnimplementedMarketdataServer
// for forward compatibility
type MarketdataServer interface {
	GetExchangeFundingRates(context.Context, *GetExchangeFundingRatesRequest) (*GetExchangeFundingRatesResponse, error)
	PublishLatestPriceInformation(context.Context, *PublishLatestPriceInformationRequest) (*PublishLatestPriceInformationResponse, error)
	PublishVolatilityInformation(context.Context, *PublishVolatilityInformationRequest) (*PublishVolatilityInformationResponse, error)
	mustEmbedUnimplementedMarketdataServer()
}

// UnimplementedMarketdataServer must be embedded to have forward compatible implementations.
type UnimplementedMarketdataServer struct {
}

func (*UnimplementedMarketdataServer) GetExchangeFundingRates(context.Context, *GetExchangeFundingRatesRequest) (*GetExchangeFundingRatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExchangeFundingRates not implemented")
}
func (*UnimplementedMarketdataServer) PublishLatestPriceInformation(context.Context, *PublishLatestPriceInformationRequest) (*PublishLatestPriceInformationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishLatestPriceInformation not implemented")
}
func (*UnimplementedMarketdataServer) PublishVolatilityInformation(context.Context, *PublishVolatilityInformationRequest) (*PublishVolatilityInformationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishVolatilityInformation not implemented")
}
func (*UnimplementedMarketdataServer) mustEmbedUnimplementedMarketdataServer() {}

func RegisterMarketdataServer(s *grpc.Server, srv MarketdataServer) {
	s.RegisterService(&_Marketdata_serviceDesc, srv)
}

func _Marketdata_GetExchangeFundingRates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExchangeFundingRatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketdataServer).GetExchangeFundingRates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/marketdata/GetExchangeFundingRates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketdataServer).GetExchangeFundingRates(ctx, req.(*GetExchangeFundingRatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketdata_PublishLatestPriceInformation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishLatestPriceInformationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketdataServer).PublishLatestPriceInformation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/marketdata/PublishLatestPriceInformation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketdataServer).PublishLatestPriceInformation(ctx, req.(*PublishLatestPriceInformationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketdata_PublishVolatilityInformation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishVolatilityInformationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketdataServer).PublishVolatilityInformation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/marketdata/PublishVolatilityInformation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketdataServer).PublishVolatilityInformation(ctx, req.(*PublishVolatilityInformationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Marketdata_serviceDesc = grpc.ServiceDesc{
	ServiceName: "marketdata",
	HandlerType: (*MarketdataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetExchangeFundingRates",
			Handler:    _Marketdata_GetExchangeFundingRates_Handler,
		},
		{
			MethodName: "PublishLatestPriceInformation",
			Handler:    _Marketdata_PublishLatestPriceInformation_Handler,
		},
		{
			MethodName: "PublishVolatilityInformation",
			Handler:    _Marketdata_PublishVolatilityInformation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "s.market-data/proto/marketdata.proto",
}
