// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: s.bookmarker/proto/bookmarker.proto

package bookmarkerproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TmpPingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *TmpPingRequest) Reset() {
	*x = TmpPingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_bookmarker_proto_bookmarker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TmpPingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TmpPingRequest) ProtoMessage() {}

func (x *TmpPingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_s_bookmarker_proto_bookmarker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TmpPingRequest.ProtoReflect.Descriptor instead.
func (*TmpPingRequest) Descriptor() ([]byte, []int) {
	return file_s_bookmarker_proto_bookmarker_proto_rawDescGZIP(), []int{0}
}

func (x *TmpPingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TmpPingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *TmpPingResponse) Reset() {
	*x = TmpPingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_bookmarker_proto_bookmarker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TmpPingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TmpPingResponse) ProtoMessage() {}

func (x *TmpPingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_s_bookmarker_proto_bookmarker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TmpPingResponse.ProtoReflect.Descriptor instead.
func (*TmpPingResponse) Descriptor() ([]byte, []int) {
	return file_s_bookmarker_proto_bookmarker_proto_rawDescGZIP(), []int{1}
}

func (x *TmpPingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_s_bookmarker_proto_bookmarker_proto protoreflect.FileDescriptor

var file_s_bookmarker_proto_bookmarker_proto_rawDesc = []byte{
	0x0a, 0x23, 0x73, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x0e, 0x54, 0x6d, 0x70, 0x50, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x2b, 0x0a, 0x0f, 0x54, 0x6d, 0x70, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x3c,
	0x0a, 0x0a, 0x62, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x12, 0x2e, 0x0a, 0x07,
	0x54, 0x6d, 0x70, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x0f, 0x2e, 0x54, 0x6d, 0x70, 0x50, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x54, 0x6d, 0x70, 0x50, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2d, 0x5a, 0x2b,
	0x73, 0x77, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x74, 0x61, 0x69, 0x6c, 0x2f, 0x73, 0x2e, 0x62, 0x69,
	0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x62, 0x6f, 0x6f, 0x6b,
	0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_s_bookmarker_proto_bookmarker_proto_rawDescOnce sync.Once
	file_s_bookmarker_proto_bookmarker_proto_rawDescData = file_s_bookmarker_proto_bookmarker_proto_rawDesc
)

func file_s_bookmarker_proto_bookmarker_proto_rawDescGZIP() []byte {
	file_s_bookmarker_proto_bookmarker_proto_rawDescOnce.Do(func() {
		file_s_bookmarker_proto_bookmarker_proto_rawDescData = protoimpl.X.CompressGZIP(file_s_bookmarker_proto_bookmarker_proto_rawDescData)
	})
	return file_s_bookmarker_proto_bookmarker_proto_rawDescData
}

var file_s_bookmarker_proto_bookmarker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_s_bookmarker_proto_bookmarker_proto_goTypes = []interface{}{
	(*TmpPingRequest)(nil),  // 0: TmpPingRequest
	(*TmpPingResponse)(nil), // 1: TmpPingResponse
}
var file_s_bookmarker_proto_bookmarker_proto_depIdxs = []int32{
	0, // 0: bookmarker.TmpPing:input_type -> TmpPingRequest
	1, // 1: bookmarker.TmpPing:output_type -> TmpPingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_s_bookmarker_proto_bookmarker_proto_init() }
func file_s_bookmarker_proto_bookmarker_proto_init() {
	if File_s_bookmarker_proto_bookmarker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_s_bookmarker_proto_bookmarker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TmpPingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_bookmarker_proto_bookmarker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TmpPingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_s_bookmarker_proto_bookmarker_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_s_bookmarker_proto_bookmarker_proto_goTypes,
		DependencyIndexes: file_s_bookmarker_proto_bookmarker_proto_depIdxs,
		MessageInfos:      file_s_bookmarker_proto_bookmarker_proto_msgTypes,
	}.Build()
	File_s_bookmarker_proto_bookmarker_proto = out.File
	file_s_bookmarker_proto_bookmarker_proto_rawDesc = nil
	file_s_bookmarker_proto_bookmarker_proto_goTypes = nil
	file_s_bookmarker_proto_bookmarker_proto_depIdxs = nil
}
