// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.17.3
// source: s.payments/proto/payments.proto

package paymentsproto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PaymentType int32

const (
	PaymentType_FUTURES PaymentType = 0
)

// Enum value maps for PaymentType.
var (
	PaymentType_name = map[int32]string{
		0: "FUTURES",
	}
	PaymentType_value = map[string]int32{
		"FUTURES": 0,
	}
)

func (x PaymentType) Enum() *PaymentType {
	p := new(PaymentType)
	*p = x
	return p
}

func (x PaymentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentType) Descriptor() protoreflect.EnumDescriptor {
	return file_s_payments_proto_payments_proto_enumTypes[0].Descriptor()
}

func (PaymentType) Type() protoreflect.EnumType {
	return &file_s_payments_proto_payments_proto_enumTypes[0]
}

func (x PaymentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentType.Descriptor instead.
func (PaymentType) EnumDescriptor() ([]byte, []int) {
	return file_s_payments_proto_payments_proto_rawDescGZIP(), []int{0}
}

type SubscriptionReminderType int32

const (
	SubscriptionReminderType_MINUS_40_HOURS SubscriptionReminderType = 0
	SubscriptionReminderType_MINUS_4_HOURS  SubscriptionReminderType = 1
	SubscriptionReminderType_MINUS_1_HOUR   SubscriptionReminderType = 2
)

// Enum value maps for SubscriptionReminderType.
var (
	SubscriptionReminderType_name = map[int32]string{
		0: "MINUS_40_HOURS",
		1: "MINUS_4_HOURS",
		2: "MINUS_1_HOUR",
	}
	SubscriptionReminderType_value = map[string]int32{
		"MINUS_40_HOURS": 0,
		"MINUS_4_HOURS":  1,
		"MINUS_1_HOUR":   2,
	}
)

func (x SubscriptionReminderType) Enum() *SubscriptionReminderType {
	p := new(SubscriptionReminderType)
	*p = x
	return p
}

func (x SubscriptionReminderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubscriptionReminderType) Descriptor() protoreflect.EnumDescriptor {
	return file_s_payments_proto_payments_proto_enumTypes[1].Descriptor()
}

func (SubscriptionReminderType) Type() protoreflect.EnumType {
	return &file_s_payments_proto_payments_proto_enumTypes[1]
}

func (x SubscriptionReminderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubscriptionReminderType.Descriptor instead.
func (SubscriptionReminderType) EnumDescriptor() ([]byte, []int) {
	return file_s_payments_proto_payments_proto_rawDescGZIP(), []int{1}
}

type RegisterPaymentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId        string  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TransactionId string  `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	AmountInUsdt  float32 `protobuf:"fixed32,3,opt,name=amount_in_usdt,json=amountInUsdt,proto3" json:"amount_in_usdt,omitempty"`
	AuditNote     string  `protobuf:"bytes,4,opt,name=audit_note,json=auditNote,proto3" json:"audit_note,omitempty"`
}

func (x *RegisterPaymentRequest) Reset() {
	*x = RegisterPaymentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_payments_proto_payments_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPaymentRequest) ProtoMessage() {}

func (x *RegisterPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_s_payments_proto_payments_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPaymentRequest.ProtoReflect.Descriptor instead.
func (*RegisterPaymentRequest) Descriptor() ([]byte, []int) {
	return file_s_payments_proto_payments_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterPaymentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterPaymentRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *RegisterPaymentRequest) GetAmountInUsdt() float32 {
	if x != nil {
		return x.AmountInUsdt
	}
	return 0
}

func (x *RegisterPaymentRequest) GetAuditNote() string {
	if x != nil {
		return x.AuditNote
	}
	return ""
}

type RegisterPaymentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegisterPaymentResponse) Reset() {
	*x = RegisterPaymentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_payments_proto_payments_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPaymentResponse) ProtoMessage() {}

func (x *RegisterPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_s_payments_proto_payments_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPaymentResponse.ProtoReflect.Descriptor instead.
func (*RegisterPaymentResponse) Descriptor() ([]byte, []int) {
	return file_s_payments_proto_payments_proto_rawDescGZIP(), []int{1}
}

type EnforceSubscriptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActorId string `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Force   bool   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
}

func (x *EnforceSubscriptionRequest) Reset() {
	*x = EnforceSubscriptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_payments_proto_payments_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnforceSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnforceSubscriptionRequest) ProtoMessage() {}

func (x *EnforceSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_s_payments_proto_payments_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnforceSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*EnforceSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_s_payments_proto_payments_proto_rawDescGZIP(), []int{2}
}

func (x *EnforceSubscriptionRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *EnforceSubscriptionRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type EnforceSubscriptionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EnforceSubscriptionResponse) Reset() {
	*x = EnforceSubscriptionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_payments_proto_payments_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnforceSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnforceSubscriptionResponse) ProtoMessage() {}

func (x *EnforceSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_s_payments_proto_payments_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnforceSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*EnforceSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_s_payments_proto_payments_proto_rawDescGZIP(), []int{3}
}

type PublishSubscriptionReminderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReminderType SubscriptionReminderType `protobuf:"varint,1,opt,name=reminder_type,json=reminderType,proto3,enum=SubscriptionReminderType" json:"reminder_type,omitempty"`
	ActorId      string                   `protobuf:"bytes,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Force        bool                     `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
}

func (x *PublishSubscriptionReminderRequest) Reset() {
	*x = PublishSubscriptionReminderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_payments_proto_payments_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishSubscriptionReminderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishSubscriptionReminderRequest) ProtoMessage() {}

func (x *PublishSubscriptionReminderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_s_payments_proto_payments_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishSubscriptionReminderRequest.ProtoReflect.Descriptor instead.
func (*PublishSubscriptionReminderRequest) Descriptor() ([]byte, []int) {
	return file_s_payments_proto_payments_proto_rawDescGZIP(), []int{4}
}

func (x *PublishSubscriptionReminderRequest) GetReminderType() SubscriptionReminderType {
	if x != nil {
		return x.ReminderType
	}
	return SubscriptionReminderType_MINUS_40_HOURS
}

func (x *PublishSubscriptionReminderRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *PublishSubscriptionReminderRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type PublishSubscriptionReminderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *PublishSubscriptionReminderResponse) Reset() {
	*x = PublishSubscriptionReminderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_payments_proto_payments_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishSubscriptionReminderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishSubscriptionReminderResponse) ProtoMessage() {}

func (x *PublishSubscriptionReminderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_s_payments_proto_payments_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishSubscriptionReminderResponse.ProtoReflect.Descriptor instead.
func (*PublishSubscriptionReminderResponse) Descriptor() ([]byte, []int) {
	return file_s_payments_proto_payments_proto_rawDescGZIP(), []int{5}
}

func (x *PublishSubscriptionReminderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_s_payments_proto_payments_proto protoreflect.FileDescriptor

var file_s_payments_proto_payments_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x73, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x9d, 0x01, 0x0a, 0x16, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x50, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x6e, 0x5f, 0x75, 0x73, 0x64, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x0c, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x55, 0x73,
	0x64, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x75, 0x64, 0x69, 0x74, 0x5f, 0x6e, 0x6f, 0x74, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x75, 0x64, 0x69, 0x74, 0x4e, 0x6f, 0x74,
	0x65, 0x22, 0x19, 0x0a, 0x17, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x50, 0x61, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4d, 0x0a, 0x1a,
	0x45, 0x6e, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x63,
	0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63,
	0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x22, 0x1d, 0x0a, 0x1b, 0x45,
	0x6e, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x95, 0x01, 0x0a, 0x22, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x3e, 0x0a, 0x0d, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x0c, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x66, 0x6f, 0x72, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6f, 0x72,
	0x63, 0x65, 0x22, 0x3f, 0x0a, 0x23, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x53, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x2a, 0x1a, 0x0a, 0x0b, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x46, 0x55, 0x54, 0x55, 0x52, 0x45, 0x53, 0x10, 0x00, 0x2a,
	0x53, 0x0a, 0x18, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x0e, 0x4d,
	0x49, 0x4e, 0x55, 0x53, 0x5f, 0x34, 0x30, 0x5f, 0x48, 0x4f, 0x55, 0x52, 0x53, 0x10, 0x00, 0x12,
	0x11, 0x0a, 0x0d, 0x4d, 0x49, 0x4e, 0x55, 0x53, 0x5f, 0x34, 0x5f, 0x48, 0x4f, 0x55, 0x52, 0x53,
	0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x4d, 0x49, 0x4e, 0x55, 0x53, 0x5f, 0x31, 0x5f, 0x48, 0x4f,
	0x55, 0x52, 0x10, 0x02, 0x32, 0x92, 0x02, 0x0a, 0x08, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x12, 0x46, 0x0a, 0x0f, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x50, 0x61, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x50,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x13, 0x45, 0x6e, 0x66,
	0x6f, 0x72, 0x63, 0x65, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x1b, 0x2e, 0x45, 0x6e, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e,
	0x45, 0x6e, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6a, 0x0a,
	0x1b, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x23, 0x2e, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x24, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x12, 0x5a, 0x10, 0x2e, 0x2f, 0x3b,
	0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_s_payments_proto_payments_proto_rawDescOnce sync.Once
	file_s_payments_proto_payments_proto_rawDescData = file_s_payments_proto_payments_proto_rawDesc
)

func file_s_payments_proto_payments_proto_rawDescGZIP() []byte {
	file_s_payments_proto_payments_proto_rawDescOnce.Do(func() {
		file_s_payments_proto_payments_proto_rawDescData = protoimpl.X.CompressGZIP(file_s_payments_proto_payments_proto_rawDescData)
	})
	return file_s_payments_proto_payments_proto_rawDescData
}

var file_s_payments_proto_payments_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_s_payments_proto_payments_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_s_payments_proto_payments_proto_goTypes = []interface{}{
	(PaymentType)(0),                            // 0: PaymentType
	(SubscriptionReminderType)(0),               // 1: SubscriptionReminderType
	(*RegisterPaymentRequest)(nil),              // 2: RegisterPaymentRequest
	(*RegisterPaymentResponse)(nil),             // 3: RegisterPaymentResponse
	(*EnforceSubscriptionRequest)(nil),          // 4: EnforceSubscriptionRequest
	(*EnforceSubscriptionResponse)(nil),         // 5: EnforceSubscriptionResponse
	(*PublishSubscriptionReminderRequest)(nil),  // 6: PublishSubscriptionReminderRequest
	(*PublishSubscriptionReminderResponse)(nil), // 7: PublishSubscriptionReminderResponse
}
var file_s_payments_proto_payments_proto_depIdxs = []int32{
	1, // 0: PublishSubscriptionReminderRequest.reminder_type:type_name -> SubscriptionReminderType
	2, // 1: payments.RegisterPayment:input_type -> RegisterPaymentRequest
	4, // 2: payments.EnforceSubscription:input_type -> EnforceSubscriptionRequest
	6, // 3: payments.PublishSubscriptionReminder:input_type -> PublishSubscriptionReminderRequest
	3, // 4: payments.RegisterPayment:output_type -> RegisterPaymentResponse
	5, // 5: payments.EnforceSubscription:output_type -> EnforceSubscriptionResponse
	7, // 6: payments.PublishSubscriptionReminder:output_type -> PublishSubscriptionReminderResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_s_payments_proto_payments_proto_init() }
func file_s_payments_proto_payments_proto_init() {
	if File_s_payments_proto_payments_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_s_payments_proto_payments_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterPaymentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_payments_proto_payments_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterPaymentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_payments_proto_payments_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnforceSubscriptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_payments_proto_payments_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnforceSubscriptionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_payments_proto_payments_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishSubscriptionReminderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_payments_proto_payments_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishSubscriptionReminderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_s_payments_proto_payments_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_s_payments_proto_payments_proto_goTypes,
		DependencyIndexes: file_s_payments_proto_payments_proto_depIdxs,
		EnumInfos:         file_s_payments_proto_payments_proto_enumTypes,
		MessageInfos:      file_s_payments_proto_payments_proto_msgTypes,
	}.Build()
	File_s_payments_proto_payments_proto = out.File
	file_s_payments_proto_payments_proto_rawDesc = nil
	file_s_payments_proto_payments_proto_goTypes = nil
	file_s_payments_proto_payments_proto_depIdxs = nil
}
