apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.gmon/routing-name: $(SERVICE_NAME)
    birdperch.io/routing-name: $(SERVICE_NAME)
    birdperch.io/service-type: $(SERVICE_TYPE)
  name: s-
spec:
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: birdperch.io.$(SERVICE_NAME)
      birdperch.io/routing-name: $(SERVICE_NAME)
  strategy:
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 20%
  template:
    metadata:
      annotations:
      labels:
        app: birdperch.io.$(SERVICE_NAME)
        birdperch.io/routing-name: $(SERVICE_NAME)
        birdperch.io/service-type: $(SERVICE_TYPE)
    spec:
      containers:
      - args:
        - -cluster
        env:
        - name: PORT
          value: "8080"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: LISTEN_ADDR
          value: 127.0.0.1:8080
        - name: GOMAXPROCS
          value: "1"
        image: templated
        name: s-
        readinessProbe:
          httpGet:
            httpHeaders:
            - name: Host
              value: $(SERVICE_NAME)
            path: /ping
            port: 80
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
        securityContext:
          readOnlyRootFilesystem: true
      - command:
        - go run $(SERVICE_NAME)
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: LIMIT_CORES
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: limits.cpu
        image: 638234331039.dkr.ecr.us-east-2.amazonaws.com/swallowtail-arm:swallowtail.$(SERVICE_NAME)
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - nc -w 30 127.0.0.1 9109 || true
      serviceAccountName: s-
